import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // Initialize language from localStorage on first render
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language') as Language | null;
      if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'zh')) {
        return savedLanguage;
      }
    }
    return 'zh';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        return key; // Return key if translation not found
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

// Translation dictionary
const translations: Record<Language, any> = {
  en: {
    // Navigation
    nav: {
      home: 'Home',
      myAvatars: 'My Avatars',
      store: 'Store',
      cart: 'Cart',
      myCollection: 'My Collection',
      featureRequests: 'Feature Requests',
      faq: 'FAQ',
      tutorials: 'Tutorials',
      updates: 'Updates',
      credits: 'Credits',
      licenses: 'Licenses',
      blog: 'Blog',
      artists: 'Artists',
      publishingTool: 'Publishing Tool',
      assetManagement: 'Asset Management',
      settings: 'Settings',
      signOut: 'Sign out',
    },
    // Home page
    home: {
      title: 'Welcome to Genji Studio',
      subtitle: 'Create and manage your avatar projects with ease',
      whatsNew: "What's New",
      startersPack: 'Introducing Starters Pack',
      startersDesc: 'Your perfect starting point with essential items, basic clothing, and foundational accessories',
      exploreNow: 'Explore Now',
      totalProjects: 'Total Projects',
      creditBalance: 'Credit Balance',
      published: 'Published',
      quickActions: 'Quick Actions',
      communityVoting: 'Community Voting',
      votingTitle: 'What pack would you like to see next?',
      scifi: 'Scifi',
      fantasy: 'Fantasy',
      asian: 'Asian',
      military: 'Military',
      vote: 'Vote',
    },
    // My Avatars
    avatars: {
      title: 'My Avatars',
      projects: 'My Projects',
      templates: 'Template Avatars',
      createNew: 'Create New',
      edit: 'Edit',
      delete: 'Delete',
      duplicate: 'Duplicate',
      export: 'Export',
      share: 'Share',
      useTemplate: 'Use Template',
      myProjects: 'My Projects',
      noPreview: 'No preview',
      published: 'Published',
      noProjects: 'No projects yet',
      createFirst: 'Create your first project',
      createNewTitle: 'Create New Project',
      createNewDesc: 'Give your avatar project a name to get started',
      projectName: 'Project Name',
      projectNamePlaceholder: 'Enter project name',
      creating: 'Creating...',
      createProject: 'Create Project',
      createSuccess: 'Project created successfully',
      nameRequired: 'Please enter a project name',
    },
    // Store
    store: {
      title: 'Store',
      personalLicense: 'Personal License',
      commercialLicense: 'Commercial License',
      addedToCart: 'Item added to cart!',
      searchPlaceholder: 'Search assets...',
      all: 'All',
      asset: 'asset',
      assets: 'assets',
      found: 'found',
      noAssetsFound: 'No assets found',
      adjustSearch: 'Try adjusting your search or filter',
      clothing: 'Clothing',
      hair: 'Hair',
      face: 'Face',
      accessories: 'Accessories',
      animations: 'Animations',
      packs: 'Packs',
      fantasy: 'Fantasy',
      'sci-fi': 'Sci-Fi',
      buy: 'Buy',
      personal: 'Personal',
      commercial: 'Commercial',
      credits: 'credits',
      becomeResidentArtist: 'Become a Resident Artist',
      becomeArtistTitle: 'Become a Resident Artist',
      becomeArtistDesc: 'Join our ecosystem and start selling your high-quality 3D assets',
      artistRequirement1: 'High-Quality Assets',
      artistRequirement1Desc: 'Submit professionally created 3D models with proper optimization',
      artistRequirement2: 'Portfolio Submission',
      artistRequirement2Desc: 'Showcase your best work and previous experience',
      artistRequirement3: 'Revenue Share',
      artistRequirement3Desc: 'Earn 70% commission on every asset sold',
      emailLabel: 'Email Address',
      emailPlaceholder: 'your.email@example.com',
      submitApplication: 'Submit Application',
      applicationSent: 'Application Sent!',
      applicationSentDesc: 'Thank you for your interest. Our team will review your application and contact you soon.',
    },
    // Cart
    cart: {
      title: 'Shopping Cart',
      empty: 'Your cart is empty',
      item: 'Item',
      license: 'License',
      price: 'Price',
      quantity: 'Quantity',
      total: 'Total',
      checkout: 'Proceed to Checkout',
      remove: 'Remove',
      updateQuantity: 'Update Quantity',
    },
    // Updates
    updates: {
      title: 'Downloads & Updates',
      currentVersion: 'Current version',
      softwareUpdates: 'Software Updates',
      sdks: 'SDKs',
      download: 'Download',
      viewDocumentation: 'View Documentation',
      comingSoon: 'Coming Soon',
      released: 'Released',
      releaseNotes: 'Release Notes',
      current: 'Current',
      newer: 'Newer',
      older: 'Older',
      beta: 'Beta',
      final: 'Final',
    },
    // Tutorials
    tutorials: {
      title: 'Tutorials',
      gettingStarted: 'Getting Started',
      avatarCreation: 'Avatar Creation',
      storeGuide: 'Store Guide',
      advancedTechniques: 'Advanced Techniques',
    },
    // Credits
    credits: {
      title: 'Credits',
      subtitle: 'Purchase credits to export assets and buy store items',
      currentBalance: 'Current Balance',
      credits: 'credits',
      purchaseCredits: 'Purchase Credits',
      purchase: 'Purchase',
      purchaseSuccess: 'Credits purchased! New balance: {balance}',
      buyCreditPacks: 'Buy Credit Packs',
      transactionHistory: 'Transaction History',
      invoiceHistory: 'Invoice History',
      downloadInvoice: 'Download Invoice',
      invoices: 'Invoices',
      invoice: 'Invoice',
      noTransactions: 'No transactions yet',
      noInvoices: 'No invoices yet',
      noInvoicesDesc: 'Purchase credits to generate invoices',
      creditsPurchase: 'Credits Purchase',
      amount: 'Amount',
      payment: 'Payment',
      date: 'Date',
      transactionId: 'Transaction ID',
      balance: 'Balance',
    },
    // Feature Requests
    featureRequests: 'Feature Requests',
    suggestNewFeatures: 'Suggest new features and vote on requests from the community',
    submitFeatureRequest: 'Submit a Feature Request',
    shareFeatureIdea: 'Share your feature idea with the community',
    newRequest: 'New Request',
    userName: 'Your Name',
    enterYourName: 'Enter your name',
    title: 'Title',
    briefTitle: 'Brief title for your feature',
    category: 'Category',
    description: 'Description',
    detailedDescription: 'Detailed description of the feature request',
    submitRequest: 'Submit Request',
    noFeatureRequests: 'No feature requests yet. Be the first to submit one!',
    // My Collection
    collection: {
      title: 'My Collection',
      asset: 'asset',
      assets: 'assets',
      owned: 'owned',
      loading: 'Loading your collection...',
      error: 'Error loading collection',
      purchased: 'Purchased',
      noAssets: 'No assets yet',
      visitStore: 'Visit the store to purchase your first asset',
      browseStore: 'Browse Store',
      licenseType: 'License Type',
      upgradeTitle: 'Upgrade License',
      upgradeDescription: 'Upgrade your license to unlock commercial use',
      item: 'Item',
      currentLicense: 'Current License',
      upgradeToCommercial: 'Upgrade to Commercial License',
      commercialBenefits: 'Use this asset in commercial projects, games, and products',
      upgradeCost: 'Upgrade Cost',
      upgradeWarning: 'This will charge your account the upgrade cost. The license will be permanently upgraded.',
      confirmUpgrade: 'Confirm Upgrade',
      upgradeSuccess: 'License upgraded successfully!',
      alreadyCommercial: 'Already has commercial license',
      upgradeFor: 'Upgrade for',
    },
    // Licenses
    licenses: {
      title: 'License Manager',
      subtitle: 'Manage your avatar licenses and understand usage rights',
      types: 'License Types',
      typesDesc: 'Choose the right license for your avatar usage',
      whatsIncluded: "What's included:",
      legalDocs: 'Legal Documents',
      legalDocsDesc: 'Review our terms and licensing agreements',
      termsTitle: 'Terms & Conditions',
      termsDesc: 'General terms of service',
      eulaDesc: 'End User License Agreement',
      activeLicenses: 'Your Active Licenses',
      activeLicensesDesc: 'Licenses acquired through avatar downloads',
      licenseKey: 'License Key',
      created: 'Created',
      expires: 'Expires',
      noLicenses: 'No active licenses yet. Download an avatar to acquire a license.',
      personal: 'Personal License',
      commercial: 'Commercial License',
      indieGame: 'Indie Game License',
      personalDesc: 'For personal, non-commercial use only',
      commercialDesc: 'For commercial projects and businesses',
      indieDesc: 'For indie game developers',
      viewLicenses: 'View Active Licenses',
      manageLicenses: 'Manage Licenses',
      termsConditions: 'Terms & Conditions',
      eula: 'EULA',
      personal1: 'Use avatars for personal projects and hobbies',
      personal2: 'Non-commercial social media content',
      personal3: 'Personal portfolio and showcase',
      personal4: 'Educational and learning purposes',
      personal5: 'Not for commercial distribution or sale',
      commercial1: 'Commercial VR/AR projects and experiences',
      commercial2: 'TV commercials and advertising campaigns',
      commercial3: 'Freelance client work and commissions',
      commercial4: 'Corporate presentations and marketing',
      commercial5: 'Commercial video production',
      commercial6: 'Unlimited revenue - no restrictions',
      indie1: 'Use in commercial game development',
      indie2: 'PC, console, and mobile game releases',
      indie3: 'Multiplayer and online games',
      indie4: 'Game asset integration and customization',
      indie5: 'Valid for studios exceeding $200K annual revenue',
      indie6: 'Royalty-free usage in shipped games',
    },
    // Legal
    legal: {
      termsTitle: 'Terms and Conditions',
      termsSection1Title: 'Acceptance of Terms',
      termsSection1Content: 'By accessing and using Genji Studio, you accept and agree to be bound by the terms and provision of this agreement.',
      termsSection2Title: 'Use License',
      termsSection2Content: 'Permission is granted to temporarily download one copy of the materials (information or software) on Genji Studio for personal, non-commercial transitory viewing only.',
      termsSection3Title: 'Disclaimer',
      termsSection3Content: 'The materials on Genji Studio are provided on an as-is basis. Genji makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.',
      termsSection4Title: 'Limitations',
      termsSection4Content: 'In no event shall Genji or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Genji Studio.',
      termsSection5Title: 'Accuracy of Materials',
      termsSection5Content: 'The materials appearing on Genji Studio could include technical, typographical, or photographic errors. Genji does not warrant that any of the materials on Genji Studio are accurate, complete, or current.',
      termsSection6Title: 'Links',
      termsSection6Content: 'Genji has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Genji of the site. Use of any such linked website is at the user\'s own risk.',
      termsSection7Title: 'Modifications',
      termsSection7Content: 'Genji may revise these terms of service for Genji Studio at any time without notice. By using this website, you are agreeing to be bound by the then current version of these terms of service.',
      termsSection8Title: 'Governing Law',
      termsSection8Content: 'These terms and conditions are governed by and construed in accordance with the laws of the jurisdiction in which Genji operates, and you irrevocably submit to the exclusive jurisdiction of the courts in that location.',
      privacyTitle: 'Privacy Policy',
      privacySection1Title: 'Information Collection',
      privacySection1Content: 'We collect information you provide directly to us, such as when you create an account, make a purchase, or contact us for support.',
      privacySection2Title: 'How We Use Your Information',
      privacySection2Content: 'We use the information we collect to provide, maintain, and improve our services, process transactions, send transactional and promotional communications, and comply with legal obligations.',
      privacySection3Title: 'Information Sharing',
      privacySection3Content: 'We do not sell, trade, or rent your personal information to third parties. We may share information with service providers who assist us in operating our website and conducting our business.',
      privacySection4Title: 'Data Security',
      privacySection4Content: 'We implement appropriate technical and organizational measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.',
      privacySection5Title: 'Your Rights',
      privacySection5Content: 'You have the right to access, correct, or delete your personal information. You can manage your preferences and opt out of certain communications at any time.',
      privacySection6Title: 'Contact Us',
      privacySection6Content: 'If you have any questions about this Privacy Policy or our privacy practices, please contact us at privacy@genji.studio.',
      cookiesTitle: 'Cookies Policy',
      cookiesSection1Title: 'What Are Cookies',
      cookiesSection1Content: 'Cookies are small files stored on your device that help us remember your preferences and improve your experience on our website.',
      cookiesSection2Title: 'Types of Cookies We Use',
      cookiesSection2Content: 'We use essential cookies for website functionality, analytical cookies to understand user behavior, and preference cookies to remember your settings.',
      cookiesSection3Title: 'Third-Party Cookies',
      cookiesSection3Content: 'We may allow third-party service providers to place cookies on your device for analytics and advertising purposes.',
      cookiesSection4Title: 'Managing Cookies',
      cookiesSection4Content: 'You can control cookies through your browser settings. Most browsers allow you to refuse cookies or alert you when cookies are being sent.',
      cookiesSection5Title: 'Changes to This Policy',
      cookiesSection5Content: 'We may update this Cookies Policy from time to time. Your continued use of our website constitutes your acceptance of any changes.',
      lastUpdated: 'Last updated: January 2026',
    },
    // Common
    common: {
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      cancel: 'Cancel',
      save: 'Save',
      delete: 'Delete',
      edit: 'Edit',
      close: 'Close',
      search: 'Search',
      filter: 'Filter',
      sort: 'Sort',
      language: 'Language',
      english: 'English',
      chinese: '中文',
      signIn: 'Sign In',
      addToCart: 'Add to Cart',
      viewDetails: 'View Details',
      all: 'All',
      noResults: 'No results found',
      noResultsHint: 'Try a different search term or category',
      searchPlaceholder: 'Search assets...',
      featureSoon: 'Feature coming soon',
    },
    // History
    history: {
      title: 'Download History',
      subtitle: 'View and re-download your exported assets',
      format: 'Format',
      cost: 'Cost',
      downloaded: 'Downloaded',
      noDownloads: 'No downloads yet',
      noDownloadsDesc: 'Export an avatar to see your download history',
      selectLicense: 'Select License Type',
      selectLicenseDesc: 'Choose the license that matches your intended use for this avatar',
      personalLicense: 'Personal License',
      personalLicenseDesc: 'For personal hobby use only',
      commercialLicense: 'Commercial License',
      commercialLicenseDesc: 'For VR projects, TV commercials, freelancers',
      indieLicense: 'Indie Game License',
      indieLicenseDesc: 'Game studios with $200K+ annual revenue',
      downloadCost: 'This download will cost {cost} credits',
      confirmDownload: 'Confirm & Download',
      processing: 'Processing...',
      insufficientCredits: 'Insufficient credits',
      insufficientCreditsDesc: "You don't have enough credits. Please purchase a credit pack to continue.",
      buyCredits: 'Buy Credits',
      downloadingWith: 'Downloading with {license}',
    },
    // Invoices
    invoices: {
      subtitle: 'View your purchase history and invoices',
    },
    // Templates
    templates: {
      title: 'Template Avatars',
      subtitle: 'Start with a pre-made avatar template',
      useTemplate: 'Use Template',
      noTemplates: 'No templates available',
    },
    // Projects
    projects: {
      manageProjects: 'Manage your avatar projects',
    },
    // Product
    product: {
      notFound: 'Product not found',
      backToStore: 'Back to Store',
      techSpecs: 'Technical Specifications',
      polyCount: 'Polygon Count',
      polygons: 'polygons',
      fileFormat: 'File Format',
      fileSize: 'File Size',
      textureMaps: 'Texture Maps Included',
      chooseLicense: 'Choose License Type',
      addToCart: 'Add to Cart',
      adding: 'Adding...',
    },
    // Artists
    artists: {
      title: 'Artists',
      subtitle: 'Meet the talented creators behind our asset collection',
      collection: "'s Collection",
      collectionDesc: 'Browse all {count} items created by {name}',
      signInToAccess: 'Sign in to purchase assets and access your full collection',
      backToArtists: 'Back to Artists',
      residentArtist: 'Resident Artist',
      andreBio: 'André Ferwerda is a renowned digital artist specializing in character design, 3D modeling, and clothing creation for avatar platforms.',
      specialties: 'Specialties',
      specialty1: 'Character Design',
      specialty2: '3D Modeling',
      specialty3: 'Clothing',
      specialty4: 'Texturing',
      specialty5: 'Avatar Customization',
      visitPortfolio: 'Visit Portfolio',
      assetsInStore: 'assets in store',
      allCreations: 'All Creations',
      browseAll: 'Browse all {count} items created by {name}',
      by: 'by',
    },
    // Kanban
    kanban: {
      title: 'Asset Review Board',
      subtitle: 'Organize and review all submitted assets using Kanban workflow',
      searchPlaceholder: 'Search by title, artist, or category...',
      accessDenied: 'Access Denied',
      accessDeniedDesc: 'Only administrators can access the Kanban review board.',
      pendingReview: 'Pending Review',
      approved: 'Approved',
      revisionRequired: 'Revision Required',
      rejected: 'Rejected',
      movedTo: 'Moved asset to {status}',
      reviewAsset: 'Review Asset',
      artist: 'Artist',
      category: 'Category',
      visualQuality: 'Visual Quality',
      visualQualityPlaceholder: 'Feedback on visual quality...',
      technicalCorrectness: 'Technical Correctness',
      technicalPlaceholder: 'Feedback on technical aspects...',
      overallComments: 'Overall Comments',
      overallPlaceholder: 'Overall feedback...',
      submitReview: 'Submit Review',
      reviewSubmitted: 'Review submitted for {title}',
      reviewFailed: 'Failed to submit review',
    },
    // Blog
    blog: {
      title: 'Blog',
      subtitle: 'Latest news, press releases, and updates from Genji',
      backToBlog: 'Back to Blog',
      readMore: 'Read more',
      readArticle: 'Read Article',
      pressRelease: 'Press Release',
      mediaContact: 'Media Contact',
      latestNews: 'Latest News',
      // Genji Launch Article
      genjiTitle: 'Reblika Launches Genji: Next Generation Digital Human Platform for Unity',
      genjiSubtitle: 'A new standard for digital humans in the Unity ecosystem, built in partnership with Unity China',
      genjiDate: 'February 2026',
      genjiLocation: 'Rotterdam, Netherlands',
      genjiExcerpt: 'Reblika Software B.V., the Rotterdam based digital atelier founded in 2019, today announces the launch of Genji, a next generation digital human creation platform built specifically for the Unity ecosystem.',
      genjiContent1: 'Reblika Software B.V., the Rotterdam based digital atelier founded in 2019, today announces the launch of Genji, a next generation digital human creation platform built specifically for the Unity ecosystem.',
      genjiContent2: 'Developed by the team behind award winning hyper realistic virtual humans for global brands including LVMH, Adidas, Absolut Vodka, and Sephora, Genji represents a major strategic step toward scalable, production ready digital human technology for developers worldwide.',
      genjiContent3: 'Genji is created in partnership with Unity China under the TuanJie ecosystem, bringing advanced digital human tooling directly to Unity developers across Asia and beyond.',
      genjiSection1Title: 'A New Standard for Digital Humans in Unity',
      genjiSection1Content: 'Genji empowers developers to design, customize, and deploy high fidelity digital humans optimized for real time applications. From games and interactive storytelling to education, simulation, and AI driven characters, Genji bridges cinematic quality with runtime performance.',
      genjiSection1Bullet1: 'Seamless Unity integration',
      genjiSection1Bullet2: 'Real time facial animation and lip sync',
      genjiSection1Bullet3: 'Modular asset customization',
      genjiSection1Bullet4: 'Export ready characters optimized for production pipelines',
      genjiSection1Bullet5: 'Support for AI driven conversational avatars',
      genjiSection2Title: 'Built by Industry Veterans',
      genjiSection2Content: 'Reblika is led by Mao Lin Liao, former character artist at Sony Guerrilla Games, where he contributed to AAA game development pipelines at one of Europe\'s most renowned studios. Earlier in his career, Mao also worked on large scale digital character productions including projects connected to Disney feature films, gaining deep expertise in cinematic quality asset creation.\n\nHe is also the creative mind behind the groundbreaking CGI avatar Sweetie, developed in collaboration with Terre des Hommes to identify online predators. The project won 13 Cannes Lions including the Grand Prix for Good and became a global case study in digital character innovation.\n\nSince formally launching Reblika in 2019 together with Co-Founder Mark van Oel, the team has translated that high fidelity expertise into commercial and scalable digital human solutions for fashion, entertainment, and technology leaders worldwide.\n\nWith Genji, that same level of craft and production discipline becomes accessible to Unity developers at scale.',
      genjiSection3Title: 'Strategic Expansion into Asia',
      genjiSection3Content: 'The collaboration with Unity China marks a significant milestone in Reblika\'s international expansion. By integrating Genji into the TuanJie ecosystem, developers gain access to localized support, optimized workflows, and a streamlined path to bringing digital humans into production.\n\nThis partnership strengthens the bridge between European digital craftsmanship and the rapidly growing Asian interactive technology market.',
      genjiSection4Title: 'Availability',
      genjiSection4Content: 'Genji and the Genji SDK will be available at launch through the Unity China ecosystem. Additional technical documentation, developer resources, and early access programs will be announced soon.',
      genjiCarouselTitle: 'Reblika Launches Genji',
      genjiCarouselDesc: 'Next generation digital human creation platform built specifically for the Unity ecosystem, in partnership with Unity China.',
    },
    // Landing page
    landing: {
      signIn: 'Sign In',
      signInDesc: 'Sign in to access your studio',
      gallery: 'Gallery',
      // About / 1-pager
      about: {
        badge: 'Production Ready',
        heroHeadline: 'Production Ready',
        heroHeadlineAccent: 'Game Characters',
        heroSubtitle: 'Create fully rigged characters for your game directly in the browser.',
        heroSubtitle2: 'No rigging. No retopology. No pipeline headaches.',
        startBuilding: 'Start Building',
        viewCharacters: 'View Characters',
        browseCharacters: 'Browse Characters',
        // Section 2
        s2Title: 'Characters ready',
        s2TitleAccent: 'for production',
        s2Body: 'Creating characters for games normally requires multiple steps and tools — modelling, rigging, retopology, shader setup, and engine integration. Genji removes the technical work and provides characters that are already ready for production.',
        s2ListIntro: 'Each character includes:',
        s2Feature1: 'Professional rig',
        s2Feature2: 'Optimized topology',
        s2Feature3: 'Animation ready skeleton',
        s2Feature4: 'Game ready shaders for skin and hair',
        s2Feature5: 'Real time optimized assets',
        s2Footer: 'Developers can immediately use the characters inside their game projects.',
        // Section 3
        s3Title: 'How Genji works',
        s3Subtitle: 'Three steps from character to game engine',
        s3Step1Title: 'Choose a character',
        s3Step1Desc: 'Start from the Genji character library.',
        s3Step2Title: 'Customize',
        s3Step2Desc: 'Change the face, hair and materials to match your hero character.',
        s3Step3Title: 'Export',
        s3Step3Desc: 'Download characters ready to use in your game engine.',
        // Section 4
        s4Title: 'Customize faces',
        s4TitleAccent: 'without re-rigging',
        s4Body1: 'Traditional pipelines lock characters to a single face and identity. Changing the face normally requires rebuilding topology and re-rigging the character.',
        s4Body2: 'Genji allows developers to modify or completely replace the face while preserving the original rig.',
        s4Highlight: 'Create many characters from one production rig.',
        // Section 5
        s5Title: 'Export to your',
        s5TitleAccent: 'favorite tools',
        s5Body: 'Characters can be exported to common game engines and content creation tools, allowing developers to quickly integrate characters into their existing workflow.',
        s5Feature1: 'Unity export',
        s5Feature2: 'Unreal Engine export',
        s5Feature3: 'Compatible with Maya and Blender pipelines',
        s5Feature4: 'GLTF based character pipeline',
        // Section 6
        s6Title: 'Built for',
        s6TitleAccent: 'real time games',
        s6Body: 'Genji characters are optimized for real time performance, ensuring they run efficiently inside game engines without additional cleanup.',
        s6Card1Title: 'Optimized topology',
        s6Card1Desc: 'Clean mesh structure designed for real time rendering',
        s6Card2Title: 'Game ready skin shaders',
        s6Card2Desc: 'Production quality skin materials out of the box',
        s6Card3Title: 'Hair card rendering',
        s6Card3Desc: 'Real time hair using optimized card-based techniques for game engines',
        s6Card4Title: 'Lightweight assets',
        s6Card4Desc: 'Fast loading assets for quick integration and smooth performance',
        // Section 7 CTA
        s7Title: 'Build your next game character',
        s7TitleAccent: 'faster',
      },
      // FAQ
      faq: {
        title: 'Frequently Asked Questions',
        subtitle: 'Everything you need to know about Genji Studio',
        devTab: 'For Developers',
        artistTab: 'For Artists',
        q1: 'What game engines does Genji support?',
        a1: 'Genji currently supports Unity with Unreal Engine support coming soon. Characters are exported in GLTF format which is compatible with most modern game engines and 3D tools including Maya and Blender.',
        q2: 'Do I need rigging experience to use Genji?',
        a2: 'No. Genji characters come pre-rigged and ready to use. You can customize faces, hair, and materials without any knowledge of rigging or topology.',
        q3: 'Can I use Genji characters in commercial games?',
        a3: 'Yes. With a Commercial License, you can use Genji characters in commercial game projects, apps, and products. Check the Store for license options.',
        q4: 'How do I export a character to Unity?',
        a4: 'After customizing your character in Genji Studio, click Export and select Unity as your target. The exported package includes the mesh, rig, materials, and textures ready to import.',
        q5: 'Can I sell assets on the Genji Store?',
        a5: 'Yes. Apply to become a Resident Artist through the Store page. Approved artists earn 70% commission on every sale.',
        q6: 'What file formats are supported?',
        a6: 'Genji uses a GLTF-based pipeline. Export packages include FBX and GLTF formats with textures and materials bundled for Unity and Unreal Engine.',
        q7: 'How do I submit assets to the store?',
        a7: 'Use the Publishing Tool in the dashboard to upload and submit your assets for review. Our team reviews all submissions for quality before they go live.',
        q8: 'What are the technical requirements for submitted assets?',
        a8: 'Assets must meet our quality standards: optimized topology, proper UV unwrapping, PBR materials, and a clean rig. Detailed guidelines are available in the Publishing Tool.',
      },
    },
    // Footer
    footer: {
      terms: 'Terms & Conditions',
      privacy: 'Privacy Statement',
      cookies: 'Cookies Policy',
      copyright: '© 2026 Genji',
    },
    // Home hero (gallery page)
    hero: {
      headline: 'GENJI',
      subheadline: 'Game Characters',
      subtitle: 'Create fully rigged characters for your game directly in the browser. No rigging. No retopology. No pipeline headaches.',
      browseCharacters: 'Browse Characters',
      learnMore: 'Learn More',
    },
    // Tutorials panel
    tutorialsPanel: {
      title: 'Tutorials',
      subtitle: 'Learn how to get the most out of Genji Studio',
      comingSoon: 'Coming Soon',
      comingSoonDesc: 'Video tutorial in production',
      intro: 'Introduction to Genji',
      exportUnity: 'Export to Unity',
      exportUnreal: 'Export to Unreal',
    },
  },
  zh: {
    // Navigation
    nav: {
      home: '首页',
      myAvatars: '我的头像',
      store: '商店',
      cart: '购物车',
      myCollection: '我的收藏',
      featureRequests: '功能请求',
      faq: '常见问题',
      tutorials: '教程',
      updates: '更新',
      credits: '积分',
      licenses: '许可证',
      blog: '博客',
      artists: '艺术家',
      publishingTool: '发布工具',
      assetManagement: '资产管理',
      settings: '设置',
      signOut: '退出登录',
    },
    // Home page
    home: {
      title: '欢迎来到 亘吉 Studio',
      subtitle: '轻松创建和管理您的头像项目',
      whatsNew: '最新消息',
      startersPack: '推出初学者包',
      startersDesc: '您的完美起点，包含必要的物品、基本服装和基础配件',
      exploreNow: '立即探索',
      totalProjects: '总项目数',
      creditBalance: '积分余额',
      published: '已发布',
      quickActions: '快速操作',
      communityVoting: '社区投票',
      votingTitle: '您希望看到哪个包？',
      scifi: '科幻',
      fantasy: '奇幻',
      asian: '亚洲',
      military: '军事',
      vote: '投票',
    },
    // My Avatars
    avatars: {
      title: '我的头像',
      projects: '我的项目',
      templates: '模板头像',
      createNew: '新建',
      edit: '编辑',
      delete: '删除',
      duplicate: '复制',
      export: '导出',
      share: '分享',
      useTemplate: '使用模板',
      myProjects: '我的项目',
      noPreview: '无预览',
      published: '已发布',
      noProjects: '暂无项目',
      createFirst: '创建您的第一个项目',
      createNewTitle: '创建新项目',
      createNewDesc: '为您的头像项目命名以开始',
      projectName: '项目名称',
      projectNamePlaceholder: '输入项目名称',
      creating: '创建中...',
      createProject: '创建项目',
      createSuccess: '项目创建成功',
      nameRequired: '请输入项目名称',
    },
    // Store
    store: {
      title: '商店',
      personalLicense: '个人许可证',
      commercialLicense: '商业许可证',
      addedToCart: '商品已加入购物车！',
      searchPlaceholder: '搜索资产...',
      all: '全部',
      asset: '个资产',
      assets: '个资产',
      found: '已找到',
      noAssetsFound: '未找到资产',
      adjustSearch: '请尝试调整搜索或筛选条件',
      clothing: '服装',
      hair: '头发',
      face: '脸部',
      accessories: '配件',
      animations: '动画',
      packs: '包',
      fantasy: '奇幻',
      'sci-fi': '科幻',
      buy: '购买',
      personal: '个人',
      commercial: '商业',
      credits: '积分',
      becomeResidentArtist: '成为驻地艺术家',
      becomeArtistTitle: '成为驻地艺术家',
      becomeArtistDesc: '加入我们的生态系统，开始销售您的高质量3D资产',
      artistRequirement1: '高质量资产',
      artistRequirement1Desc: '提交专业创建的3D模型，具有适当的优化',
      artistRequirement2: '作品集提交',
      artistRequirement2Desc: '展示您最好的作品和以前的经验',
      artistRequirement3: '收入分享',
      artistRequirement3Desc: '每次资产销售赚取70%佣金',
      emailLabel: '电子邮件地址',
      emailPlaceholder: 'your.email@example.com',
      submitApplication: '提交申请',
      applicationSent: '申请已发送！',
      applicationSentDesc: '感谢您的兴趣。我们的团队将审查您的申请并尽快与您联系。',
    },
    // Cart
    cart: {
      title: '购物车',
      empty: '您的购物车为空',
      item: '物品',
      license: '许可证',
      price: '价格',
      quantity: '数量',
      total: '总计',
      checkout: '结账',
      remove: '移除',
      updateQuantity: '更新数量',
    },
    // Updates
    updates: {
      title: '下载和更新',
      currentVersion: '当前版本',
      softwareUpdates: '软件更新',
      sdks: 'SDK',
      download: '下载',
      viewDocumentation: '查看文档',
      comingSoon: '即将推出',
      released: '发布于',
      releaseNotes: '发布说明',
      current: '当前',
      newer: '较新',
      older: '较旧',
      beta: '测试版',
      final: '正式版',
    },
    // Tutorials
    tutorials: {
      title: '教程',
      gettingStarted: '入门指南',
      avatarCreation: '头像创建',
      storeGuide: '商店指南',
      advancedTechniques: '高级技术',
    },

    // Feature Requests
    featureRequests: '功能请求',
    suggestNewFeatures: '向社区建议新功能并投票支持请求',
    submitFeatureRequest: '提交功能请求',
    shareFeatureIdea: '与社区分享您的功能想法',
    newRequest: '新请求',
    userName: '您的名字',
    enterYourName: '输入您的名字',
    title: '标题',
    briefTitle: '功能的简短标题',
    category: '类别',
    description: '描述',
    detailedDescription: '功能请求的详细描述',
    submitRequest: '提交请求',
    noFeatureRequests: '还没有功能请求。成为第一个提交的人！',
    // My Collection
    collection: {
      title: '我的收藏',
      asset: '个资产',
      assets: '个资产',
      owned: '已拥有',
      loading: '正在加载您的收藏...',
      error: '加载收藏时出错',
      purchased: '购买于',
      noAssets: '还没有资产',
      visitStore: '访问商店购买您的第一个资产',
      browseStore: '浏览商店',
      licenseType: '许可证类型',
      upgradeTitle: '升级许可证',
      upgradeDescription: '升级您的许可证以解锁商业用途',
      item: '项目',
      currentLicense: '当前许可证',
      upgradeToCommercial: '升级到商业许可证',
      commercialBenefits: '在商业项目、游戏和产品中使用此资产',
      upgradeCost: '升级成本',
      upgradeWarning: '这将向您的账户收取升级成本。许可证将永久升级。',
      confirmUpgrade: '确认升级',
      upgradeSuccess: '许可证升级成功！',
      alreadyCommercial: '已有商业许可证',
      upgradeFor: '升级费用',
    },
    // Licenses
    licenses: {
      title: '许可证管理',
      subtitle: '管理您的头像许可证并了解使用权限',
      types: '许可证类型',
      typesDesc: '为您的头像用途选择合适的许可证',
      whatsIncluded: '包含内容：',
      legalDocs: '法律文件',
      legalDocsDesc: '查看我们的条款和许可协议',
      termsTitle: '条款和条件',
      termsDesc: '一般服务条款',
      eulaDesc: '最终用户许可协议',
      activeLicenses: '您的活跃许可证',
      activeLicensesDesc: '通过头像下载获得的许可证',
      licenseKey: '许可证密钥',
      created: '创建于',
      expires: '到期于',
      noLicenses: '暂无活跃许可证。下载头像以获取许可证。',
      personal: '个人许可证',
      commercial: '商业许可证',
      indieGame: '独立游戏许可证',
      personalDesc: '仅供个人非商业使用',
      commercialDesc: '用于商业项目和企业',
      indieDesc: '为独立游戏开发者',
      viewLicenses: '查看活跃许可证',
      manageLicenses: '管理许可证',
      termsConditions: '条款和条件',
      eula: '最终用户许可协议',
      personal1: '将头像用于个人项目和爱好',
      personal2: '非商业社交媒体内容',
      personal3: '个人作品集和展示',
      personal4: '教育和学习目的',
      personal5: '不得用于商业分发或销售',
      commercial1: '商业 VR/AR 项目和体验',
      commercial2: '电视广告和营销活动',
      commercial3: '自由职业客户工作和委托',
      commercial4: '企业演示和营销',
      commercial5: '商业视频制作',
      commercial6: '无限收入 - 无限制',
      indie1: '用于商业游戏开发',
      indie2: 'PC、主机和移动游戏发行',
      indie3: '多人和在线游戏',
      indie4: '游戏资产集成和定制',
      indie5: '适用于年收入超过20万美元的工作室',
      indie6: '已发行游戏中的免版税使用',
    },
    // Blog
    blog: {
      title: '博客',
      subtitle: '来自 亘吉 的最新新闻、新闻稿和更新',
      backToBlog: '返回博客',
      readMore: '阅读更多',
      readArticle: '阅读文章',
      pressRelease: '新闻稿',
      mediaContact: '媒体联系',
      latestNews: '最新新闻',
      // 亘吉 Launch Article
      genjiTitle: 'Reblika 推出 亘吉：面向 Unity 的下一代数字人平台',
      genjiSubtitle: 'Unity 生态系统中数字人的新标准，与 Unity 中国合作打造',
      genjiDate: '2026年2月',
      genjiLocation: '荷兰鹿特丹',
      genjiExcerpt: 'Reblika Software B.V.，这家成立于2019年的鹿特丹数字工作室，今天宣布推出 亘吉，一个专为 Unity 生态系统打造的下一代数字人创建平台。',
      genjiContent1: 'Reblika Software B.V.，这家成立于2019年的鹿特丹数字工作室，今天宣布推出 亘吉，一个专为 Unity 生态系统打造的下一代数字人创建平台。',
      genjiContent2: '由曾为 LVMH、Adidas、Absolut Vodka 和 Sephora 等全球品牌打造屡获殊荣的超写实虚拟人的团队开发，亘吉 代表了向全球开发者提供可扩展、生产就绪的数字人技术的重大战略步骤。',
      genjiContent3: '亘吉 是与 Unity 中国在团结引擎生态系统下合作创建的，将先进的数字人工具直接带给亚洲及其他地区的 Unity 开发者。',
      genjiSection1Title: 'Unity 中数字人的新标准',
      genjiSection1Content: '亘吉 使开发者能够设计、定制和部署针对实时应用优化的高保真数字人。从游戏和互动叙事到教育、模拟和 AI 驱动的角色，亘吉 将电影级质量与运行时性能完美结合。',
      genjiSection1Bullet1: '无缝 Unity 集成',
      genjiSection1Bullet2: '实时面部动画和唇形同步',
      genjiSection1Bullet3: '模块化资产定制',
      genjiSection1Bullet4: '针对生产流水线优化的导出就绪角色',
      genjiSection1Bullet5: '支持 AI 驱动的对话虚拟形象',
      genjiSection2Title: '由行业资深人士打造',
      genjiSection2Content: 'Reblika 由 Mao Lin Liao 领导，他曾是 Sony Guerrilla Games 的角色艺术家，在欧洲最知名的工作室之一为 AAA 级游戏开发流水线做出了贡献。在他职业生涯的早期，Mao 还参与了大规模数字角色制作，包括与迪士尼电影相关的项目，积累了电影级质量资产创作的深厚专业知识。\n\n他也是突破性 CGI 虚拟形象 Sweetie 背后的创意人，该项目与 Terre des Hommes 合作开发，用于识别网络掠夺者。该项目赢得了13座戛纳金狮奖，包括公益类全场大奖，成为数字角色创新的全球案例研究。\n\n自2019年与联合创始人 Mark van Oel 正式创立 Reblika 以来，团队已将高保真专业知识转化为面向时尚、娱乐和科技领导者的商业化、可扩展的数字人解决方案。\n\n通过 亘吉，同样水平的工艺和生产纪律将大规模地提供给 Unity 开发者。',
      genjiSection3Title: '战略性扩展至亚洲',
      genjiSection3Content: '与 Unity 中国的合作标志着 Reblika 国际扩展的重要里程碑。通过将 亘吉 集成到团结引擎生态系统中，开发者可以获得本地化支持、优化的工作流程，以及将数字人投入生产的简化路径。\n\n这一合作加强了欧洲数字工艺与快速增长的亚洲互动技术市场之间的桥梁。',
      genjiSection4Title: '可用性',
      genjiSection4Content: '亘吉 和 亘吉 SDK 将在发布时通过 Unity 中国生态系统提供。更多技术文档、开发者资源和早期访问计划将很快公布。',
      genjiCarouselTitle: 'Reblika 推出 亘吉',
      genjiCarouselDesc: '专为 Unity 生态系统打造的下一代数字人创建平台，与 Unity 中国合作。',
    },
    // Common
    common: {
      loading: '加载中...',
      error: '错误',
      success: '成功',
      cancel: '取消',
      save: '保存',
      delete: '删除',
      edit: '编辑',
      close: '关闭',
      search: '搜索',
      filter: '筛选',
      sort: '排序',
      language: '语言',
      english: 'English',
      chinese: '中文',
      signIn: '登录',
      addToCart: '加入购物车',
      viewDetails: '查看详情',
      all: '全部',
      noResults: '未找到结果',
      noResultsHint: '请尝试不同的搜索词或分类',
      searchPlaceholder: '搜索资产...',
      featureSoon: '功能即将推出',
    },
    // History
    history: {
      title: '下载历史',
      subtitle: '查看并重新下载您的导出资产',
      format: '格式',
      cost: '费用',
      downloaded: '下载于',
      noDownloads: '暂无下载记录',
      noDownloadsDesc: '导出头像以查看下载历史',
      selectLicense: '选择许可证类型',
      selectLicenseDesc: '选择与您预期用途相符的许可证',
      personalLicense: '个人许可证',
      personalLicenseDesc: '仅供个人爱好使用',
      commercialLicense: '商业许可证',
      commercialLicenseDesc: '适用于 VR 项目、电视广告、自由职业者',
      indieLicense: '独立游戏许可证',
      indieLicenseDesc: '年收入超过20万美元的游戏工作室',
      downloadCost: '此次下载将消耗 {cost} 积分',
      confirmDownload: '确认并下载',
      processing: '处理中...',
      insufficientCredits: '积分不足',
      insufficientCreditsDesc: '您的积分不足。请购买积分包以继续。',
      buyCredits: '购买积分',
      downloadingWith: '正在使用 {license} 下载',
    },
    // Invoices
    invoices: {
      subtitle: '查看您的购买历史和发票',
    },
    // Templates
    templates: {
      title: '模板头像',
      subtitle: '从预制头像模板开始',
      useTemplate: '使用模板',
      noTemplates: '暂无可用模板',
    },
    // Projects
    projects: {
      manageProjects: '管理您的头像项目',
    },
    // Product
    product: {
      notFound: '未找到产品',
      backToStore: '返回商店',
      techSpecs: '技术规格',
      polyCount: '多边形数量',
      polygons: '个多边形',
      fileFormat: '文件格式',
      fileSize: '文件大小',
      textureMaps: '包含的贴图',
      chooseLicense: '选择许可证类型',
      addToCart: '加入购物车',
      adding: '添加中...',
    },
    // Artists
    artists: {
      title: '艺术家',
      subtitle: '认识我们资产系列背后的才华横溢的创作者',
      collection: '的作品集',
      collectionDesc: '浏览 {name} 创作的全部 {count} 件作品',
      signInToAccess: '登录以购买资产并访问您的完整收藏',
      backToArtists: '返回艺术家',
      residentArtist: '驻地艺术家',
      andreBio: 'André Ferwerda 是一位著名的数字艺术家，专注于角色设计、3D 建模和头像平台的服装创作。',
      specialties: '专业技能',
      specialty1: '角色设计',
      specialty2: '3D 建模',
      specialty3: '服装设计',
      specialty4: '贴图制作',
      specialty5: '头像定制',
      visitPortfolio: '访问作品集',
      assetsInStore: '个商店资产',
      allCreations: '全部作品',
      browseAll: '浏览 {name} 创作的全部 {count} 件作品',
      by: '作者',
    },
    // Kanban
    kanban: {
      title: '资产审核看板',
      subtitle: '使用看板工作流组织和审核所有提交的资产',
      searchPlaceholder: '按标题、艺术家或类别搜索...',
      accessDenied: '访问被拒绝',
      accessDeniedDesc: '只有管理员才能访问看板审核板。',
      pendingReview: '待审核',
      approved: '已批准',
      revisionRequired: '需要修改',
      rejected: '已拒绝',
      movedTo: '已将资产移至 {status}',
      reviewAsset: '审核资产',
      artist: '艺术家',
      category: '类别',
      visualQuality: '视觉质量',
      visualQualityPlaceholder: '关于视觉质量的反馈...',
      technicalCorrectness: '技术正确性',
      technicalPlaceholder: '关于技术方面的反馈...',
      overallComments: '总体评价',
      overallPlaceholder: '总体反馈...',
      submitReview: '提交审核',
      reviewSubmitted: '已提交 {title} 的审核',
      reviewFailed: '提交审核失败',
    },
    // Landing page
    landing: {
      signIn: '登录',
      signInDesc: '登录以访问您的工作室',
      gallery: '画廊',
      // About / 1-pager
      about: {
        badge: '生产就绪',
        heroHeadline: '生产就绪',
        heroHeadlineAccent: '游戏角色',
        heroSubtitle: '直接在浏览器中为您的游戏创建完整绑定的角色。',
        heroSubtitle2: '无需绑定。无需重拓扑。无需流程烦恼。',
        startBuilding: '开始创建',
        viewCharacters: '查看角色',
        browseCharacters: '浏览角色',
        // Section 2
        s2Title: '生产就绪的',
        s2TitleAccent: '游戏角色',
        s2Body: '为游戏创建角色通常需要多个步骤和工具——建模、绑定、重拓扑、着色器设置和引擎集成。亘吉 消除了技术工作，提供已经准备好用于生产的角色。',
        s2ListIntro: '每个角色包含：',
        s2Feature1: '专业绑定',
        s2Feature2: '优化的拓扑结构',
        s2Feature3: '动画就绪骨架',
        s2Feature4: '皮肤和头发的游戏就绪着色器',
        s2Feature5: '实时优化资产',
        s2Footer: '开发者可以立即在游戏项目中使用这些角色。',
        // Section 3
        s3Title: '亘吉 的工作原理',
        s3Subtitle: '从角色到游戏引擎的三个步骤',
        s3Step1Title: '选择角色',
        s3Step1Desc: '从 亘吉 角色库开始。',
        s3Step2Title: '自定义',
        s3Step2Desc: '更改脸部、头发和材质以匹配您的英雄角色。',
        s3Step3Title: '导出',
        s3Step3Desc: '下载可在游戏引擎中直接使用的角色。',
        // Section 4
        s4Title: '自定义脸部',
        s4TitleAccent: '无需重新绑定',
        s4Body1: '传统流程将角色锁定到单一脸部和身份。更改脸部通常需要重建拓扑并重新绑定角色。',
        s4Body2: '亘吉 允许开发者修改或完全替换脸部，同时保留原始绑定。',
        s4Highlight: '从一个生产绑定创建多个角色。',
        // Section 5
        s5Title: '导出到您',
        s5TitleAccent: '喜欢的工具',
        s5Body: '角色可以导出到常见的游戏引擎和内容创建工具，让开发者快速将角色集成到现有工作流程中。',
        s5Feature1: 'Unity 导出',
        s5Feature2: 'Unreal Engine 导出',
        s5Feature3: '兼容 Maya 和 Blender 流程',
        s5Feature4: '基于 GLTF 的角色流程',
        // Section 6
        s6Title: '专为',
        s6TitleAccent: '实时游戏打造',
        s6Body: '亘吉 角色针对实时性能进行了优化，确保它们在游戏引擎中高效运行，无需额外清理。',
        s6Card1Title: '优化的拓扑结构',
        s6Card1Desc: '专为实时渲染设计的干净网格结构',
        s6Card2Title: '游戏就绪皮肤着色器',
        s6Card2Desc: '开箱即用的生产质量皮肤材质',
        s6Card3Title: '发片渲染',
        s6Card3Desc: '使用针对游戏引擎优化的发片技术实现实时头发效果',
        s6Card4Title: '轻量级资产',
        s6Card4Desc: '快速加载资产，实现快速集成和流畅性能',
        // Section 7 CTA
        s7Title: '更快地创建您的',
        s7TitleAccent: '下一个游戏角色',
      },
      // FAQ
      faq: {
        title: '常见问题',
        subtitle: '关于 亘吉 Studio 您需要了解的一切',
        devTab: '开发者',
        artistTab: '艺术家',
        q1: '亘吉 支持哪些游戏引擎？',
        a1: '亘吉 目前支持 Unity，Unreal Engine 支持即将推出。角色以 GLTF 格式导出，兼容大多数现代游戏引擎和 3D 工具，包括 Maya 和 Blender。',
        q2: '使用 亘吉 需要绑定经验吗？',
        a2: '不需要。亘吉 角色预先绑定，可以直接使用。您可以自定义脸部、头发和材质，无需任何绑定或拓扑知识。',
        q3: '我可以在商业游戏中使用 亘吉 角色吗？',
        a3: '可以。使用商业许可证，您可以在商业游戏项目、应用程序和产品中使用 亘吉 角色。请查看商店了解许可证选项。',
        q4: '如何将角色导出到 Unity？',
        a4: '在 亘吉 Studio 中自定义角色后，点击导出并选择 Unity 作为目标。导出包包含网格、绑定、材质和纹理，可直接导入。',
        q5: '我可以在 亘吉 商店销售资产吗？',
        a5: '可以。通过商店页面申请成为驻地艺术家。获批艺术家每次销售可获得 70% 佣金。',
        q6: '支持哪些文件格式？',
        a6: '亘吉 使用基于 GLTF 的流程。导出包包含 FBX 和 GLTF 格式，附带为 Unity 和 Unreal Engine 打包的纹理和材质。',
        q7: '如何向商店提交资产？',
        a7: '使用仪表板中的发布工具上传并提交资产以供审核。我们的团队在资产上线前审核所有提交的质量。',
        q8: '提交资产的技术要求是什么？',
        a8: '资产必须符合我们的质量标准：优化的拓扑结构、正确的 UV 展开、PBR 材质和干净的绑定。详细指南可在发布工具中找到。',
      },
    },
    // Credits
    credits: {
      title: '积分',
      subtitle: '购买积分以导出资产和购买商店商品',
      currentBalance: '当前余额',
      credits: '积分',
      purchaseCredits: '购买积分',
      purchase: '购买',
      purchaseSuccess: '积分购买成功！新余额：{balance}',
      buyCreditPacks: '购买积分包',
      transactionHistory: '交易历史',
      invoiceHistory: '发票历史',
      downloadInvoice: '下载发票',
      invoices: '发票',
      invoice: '发票',
      noTransactions: '暂无交易记录',
      noInvoices: '暂无发票',
      noInvoicesDesc: '购买积分以生成发票',
      creditsPurchase: '积分购买',
      amount: '金额',
      payment: '支付',
      date: '日期',
      transactionId: '交易编号',
      balance: '余额',
    },
    // Footer
    footer: {
      terms: '条款和条件',
      privacy: '隐私声明',
      cookies: 'Cookie 政策',
      copyright: '© 2026 亘吉',
    },
    // Home hero (gallery page)
    hero: {
      headline: '亘吉',
      subheadline: '游戏角色',
      subtitle: '直接在浏览器中为您的游戏创建完整绑定的角色。无需绑定。无需重拓扑。无需流程烦恼。',
      browseCharacters: '浏览角色',
      learnMore: '了解更多',
    },
    // Tutorials panel
    tutorialsPanel: {
      title: '教程',
      subtitle: '学习如何充分利用 亘吉 Studio',
      comingSoon: '即将推出',
      comingSoonDesc: '视频教程制作中',
      intro: '亘吉 简介',
      exportUnity: '导出到 Unity',
      exportUnreal: '导出到 Unreal',
    },
    // Legal
    legal: {
      termsTitle: '条款和条件',
      privacyTitle: '隐私声明',
      cookiesTitle: 'Cookie 政策',
      lastUpdated: '最后更新：2026年1月',
    },
  },
};
